#!/usr/bin/php
<?php

$home = getenv('HOME');
if(is_string($home)) {
	define('CONFIG_FILE', "{$home}/.config/ckpunmkug/scanner.php");
	require_once(CONFIG_FILE);
}
else {
	trigger_error("Can't get `HOME` environment", E_USER_ERROR);
	exit(255);
}

set_include_path(__DIR__.'/../include');
require('block/Initialization.php');

$return = Scanner::main();
if($return !== true) {
	trigger_error("Main call returned an error", E_USER_ERROR);
	exit(255);
}
exit(0);

