#!/bin/sh
#<?php ob_end_clean(); goto start; ?>

FILE=`/usr/bin/realpath $0`
DIR=`/usr/bin/dirname ${FILE}`
BASENAME=`basename ${FILE}`

HOST="127.0.0.1"
PORT="8080"

# Help block
#{{{

HELP="
Description: The script starts the php built-in web server with authorization.
Usage: ${BASENAME} [user] <docroot>
"

if test "${1}" = "-h" -o "${1}" = "--help"
then
	/usr/bin/echo "${HELP}"
	exit 0
fi

#}}}

# Echo functions
#{{{

error ()
{
	/usr/bin/echo "Error: ${BASENAME} - ${1}" >&2
	return 255
}

notice ()
{
	/usr/bin/echo "${BASENAME} - ${1}"
	return 0
}

#}}}

# Change user and load config
#{{{

UID=`/usr/bin/id -r -u`
GID=`/usr/bin/id -r -g`

if test $UID -eq 0 -o $GID -eq 0
then
	if test -z "${1}"
	then
		error "The argument 'user' not passsed in command line"
		exit 255
	fi
	
	if test -z "${2}"
	then
		error "The argument 'docroot' not passsed in command line"
		exit 255
	fi
	
	/usr/bin/su -P -s /bin/sh -l "${1}" -c "${FILE} ${2}"
	exit 0
else	
	if test -z "${1}"
	then
		error "The argument 'docroot' not passsed in command line"
		exit 255
	fi
	export DOCROOT="${1}"
	
	export PASSWORD=`/usr/bin/apg -n 1 -m 6 -x 6 -M NCL`
fi

#}}}

# Echo info
#{{{

TEXT="
User: ${USER}
Password: ${PASSWORD}
Docroot: ${DOCROOT}
"
/usr/bin/echo "${TEXT}"

#}}}

/usr/bin/php -d auto_prepend_file=${FILE} -t ${DOCROOT} -S ${HOST}:${PORT}
exit $?

<?php start:

$user = getenv('USER', true);
if(!is_string($user)) {
	trigger_error("Environment variable 'USER' is not set", E_USER_ERROR);
	exit(255);
}

$password = getenv('PASSWORD', true);
if(!is_string($password)) {
	trigger_error("Environment variable 'PASSWORD' is not set", E_USER_ERROR);
	exit(255);
}

$authorization = function(string $user, $password)
{
	$headers = apache_request_headers();
	$r = array_key_exists('Authorization', $headers);
	if ($r !== true) {
		return(false);
	}
	
	$s = $headers['Authorization'];
	if (preg_match('/^([^\s]+)\s+([^\s]+)$/', $s, $m) !== 1) {
		return(false);
	}
	$type = $m[1];
	$credentials = $m[2];
	
	if (strcmp($type, 'Basic') !== 0) {
		return(false);
	}
	
	$s = base64_encode("{$user}:${password}");	
	if (strcmp($credentials, $s) !== 0) {
		return(false);
	}
	
	return(true);
};

if($authorization($user, $password) != true) {
	http_response_code(401);
	header('WWW-Authenticate: Basic realm="Access to the php built-in web server", charset="UTF-8"');
	exit(0);
}

unset($user, $password, $authorization);

