#!/usr/bin/php
<?php 

define('VENDOR', 'ckpunmkug');
define('PROJECT', 'tester');

set_include_path(__DIR__.'/../include');
require_once('class/C.php');
require_once('class/Args.php');
require_once('class/PHPDebugger.php');
require_once('component/phpdbg_wrapper.php');

// Args
if(true) {//{{{//
	
	Args::$description = "phpdbg wrapper";
	
	Args::add([
		"-C", "--commands-file", "<path_to_file>", "Path to file with commands of phpdbg",
		function ($string) {
			define("COMMANDS_FILE", $string);
		}, true
	]);
	
	Args::add([
		"-S", "--source-file", "<path_to_file>", "Path to php source file",
		function ($string) {
			define("SOURCE_FILE", $string);
		}, true
	]);
	
	Args::add([
		"-W", "--working-directory", "<path_to_dir>", "Path to working directory",
		function ($string) {
			define("WORKING_DIR", $string);
		}, true
	]);
	
	Args::apply();
	
	
}//}}}//

$phpdbg_wrapper = new phpdbg_wrapper(COMMANDS_FILE, SOURCE_FILE, WORKING_DIR);

