#!/bin/sh -e

/usr/bin/apt install tzdata locales keyboard-configuration console-setup
/usr/sbin/dpkg-reconfigure tzdata 
/usr/sbin/dpkg-reconfigure locales
/usr/sbin/dpkg-reconfigure keyboard-configuration
/usr/sbin/dpkg-reconfigure console-setup

/usr/bin/apt install ntpdate
/usr/bin/apt install info man-db manpages manpages-dev manpages-posix manpages-posix-dev
/usr/bin/apt install dict dictd mueller7-dict
/usr/bin/apt install lynx dnsutils whois geoip-bin telnet tcpdump nmap wget

/usr/bin/apt install xorg xfwm4 xfce4 xfce4-power-manager xfce4-terminal xfce4-screenshooter xfce4-taskmanager xfonts-terminus xfce4-xkb-plugin
/usr/bin/apt install sudo pkexec gparted apg mtools tree
/usr/bin/apt install firefox-esr git openssh-client transmission-cli
/usr/bin/apt install gimp fontforge mousepad cherrytree
/usr/bin/apt install galculator ristretto fbreader
/usr/bin/apt install alsa-utils pulseaudio mplayer gnugo
/usr/bin/apt install imagemagick xdotool xsel ffmpeg

! /usr/sbin/alsactl -L init

adduser --gecos "" user
chmod 700 /home/user
adduser user sudo
adduser user audio

echo "Base installation complete"
