#!/usr/bin/php
<?php

if(true) // Initialization
{//{{{//

	set_include_path(__DIR__.'/../include');
	require_once('class/Data.php');
	require_once('class/Args.php');
	require_once('component/ddgr.php');
	
}//}}}//

if(true) // Args used chars D, R, Q, T, P, S, F, E
{//{{{//
	
	Args::$description = "Program description";
	Args::add([
		"-D", "--database", "<path_to_file>", "Path to sqlite3 database file",
		function ($string) {
			define("DATABASE_FILE_PATH", $string);
		}, true
	]);
	Args::add([
		"-R", "--import-regions", "<path_to_file>", "Import regions list from file to database",
		function ($string) {
			define("REGIONS_FILE_PATH", $string);
		}, false
	]);
	Args::add([
		"-Q", "--import-queries", "<path_to_file>", "Import queries list from file to database",
		function ($string) {
			define("QUERIES_FILE_PATH", $string);
		}, false
	]);
	Args::add([
		"-T", "--queries-table", "<queries_table_name>", "Use this table for work with queries",
		function ($string) {
			define("QUERIES_TABLE_NAME", $string);
		}, false
	]);
	Args::add([
		"-P", "--process-ddgr", NULL, "Start process to perform search queries in ddgr",
		function () {
			define("DDGR_PROCESS", true);
		}, false
	]);
	Args::add([
		"-S", "--ddgr-statistics", NULL, "Count and show ddgr data",
		function () {
			define("DDGR_STATISTICS", true);
		}, false
	]);
	Args::add([
		"-F", "--create-results", NULL, "Parse ddgr json in to results table",
		function () {
			define("CREATE_RESULTS", true);
		}, false
	]);
	Args::add([
		"-E", "--export-urls", "<path_to_file>", "Export urls from results table to file",
		function ($string) {
			define("EXPORT_URLS_FILE_PATH", $string);
		}, false
	]);
	Args::apply();
	
}//}}}//

function main()
{
	$return = Data::open(DATABASE_FILE_PATH);
	if(!$return) {
		trigger_error("Can't open database", E_USER_WARNING);
		return(false);
	}
	
	if(defined('REGIONS_FILE_PATH')) {
		$return = ddgr::import_regions(REGIONS_FILE_PATH);
		if(!$return) {
			trigger_error("Can't import regions", E_USER_WARNING);
			return(false);
		}
	}
	
	if(defined('QUERIES_FILE_PATH')) {
		if(!defined('QUERIES_TABLE_NAME')) {
			trigger_error("Queries table name not passed in command line", E_USER_WARNING);
			return(false);
		}
		$return = ddgr::import_queries(QUERIES_FILE_PATH, QUERIES_TABLE_NAME);
		if(!$return) {
			trigger_error("Can't import queries", E_USER_WARNING);
			return(false);
		}
	}
	
	if(defined('DDGR_PROCESS')) {
		if(!defined('QUERIES_TABLE_NAME')) {
			trigger_error("Queries table name not passed in command line", E_USER_WARNING);
			return(false);
		}
		
		$return = ddgr::process(QUERIES_TABLE_NAME);
		if(!$return) {
			trigger_error("Process of ddgr failed", E_USER_WARNING);
			return(false);
		}
	}
	
	if(defined('DDGR_STATISTICS')) {
		if(!defined('QUERIES_TABLE_NAME')) {
			trigger_error("Queries table name not passed in command line", E_USER_WARNING);
			return(false);
		}
		
		$statistics = ddgr::statistics(QUERIES_TABLE_NAME);
		if(!is_array($statistics)) {
			trigger_error("Can't get statistics", E_USER_WARNING);
			return(false);
		}
		
		$text = 
///////////////////////////////////////////////////////////////{{{//
<<<HEREDOC

Statistics for queries table

Total     {$statistics["total"]}
Raw       {$statistics["raw"]}
Try       {$statistics["try"]}
Error     {$statistics["error"]}
Complete  {$statistics["complete"]}

HEREDOC;
///////////////////////////////////////////////////////////////}}}//
		echo($text);
	}
	
	if(defined('CREATE_RESULTS')) {
		if(!defined('QUERIES_TABLE_NAME')) {
			trigger_error("Queries table name not passed in command line", E_USER_WARNING);
			return(false);
		}
		
		$return = ddgr::create_results(QUERIES_TABLE_NAME);
		if(!$return) {
			trigger_error("Can't create results data", E_USER_WARNING);
			return(false);
		}
	}
	
	if(defined('EXPORT_URLS_FILE_PATH')) {
		$return = ddgr::export_urls(EXPORT_URLS_FILE_PATH);
		if(!$return) {
			trigger_error("Can't export urls to file", E_USER_WARNING);
			return(false);
		}
	}
		
	return(true);
}

$return = main();
if($return !== true) exit(255);
exit(0);

