#!/bin/sh
#<?php ob_end_clean(); goto start; ?>

HOST="127.0.0.1"
PORT="8080"

# Initialization block
#{{{

FILE=`/usr/bin/realpath $0`
DIR=`/usr/bin/dirname ${FILE}`
BASENAME=`basename ${FILE}`
SESSIONS='/tmp/8080_SESSIONS'

HELP="
Description: The script starts the php built-in web server with authorization.
Usage: ${BASENAME} [user] <docroot>
"

if test "${1}" = "-h" -o "${1}" = "--help"
then
	/usr/bin/echo "${HELP}"
	exit 0
fi

#}}}

# Echo functions
#{{{

error ()
{
	/usr/bin/echo "Error: ${BASENAME} - ${1}" >&2
	return 255
}

notice ()
{
	/usr/bin/echo "${BASENAME} - ${1}"
	return 0
}

#}}}

# Change user
#{{{

UID=`/usr/bin/id -r -u`
GID=`/usr/bin/id -r -g`

if test $UID -eq 0 -o $GID -eq 0
then
	if test -z "${1}"
	then
		error "The argument 'user' not passsed in command line"
		exit 255
	fi
	
	if test -z "${2}"
	then
		error "The argument 'docroot' not passsed in command line"
		exit 255
	fi
	
	/usr/bin/su -P -s /bin/sh -l "${1}" -c "${FILE} ${2}"
	exit 0
else	
	if test -z "${1}"
	then
		error "The argument 'docroot' not passsed in command line"
		exit 255
	fi
	export DOCROOT="${1}"
fi

export USER=`/usr/bin/whoami`
export PASSWORD=`/usr/bin/apg -n 1 -m 6 -x 6 -M NCL`

#}}}

# Echo info
#{{{

TEXT="
User: ${USER}
Password: ${PASSWORD}
Docroot: ${DOCROOT}
"
/usr/bin/echo "${TEXT}"

#}}}

trap_handler()
{
	/usr/bin/rm --force --recursive --verbose "${session_save_path}"
	exit $?
}
trap 'trap_handler' QUIT

export session_save_path="${SESSIONS}.${USER}"
if test -d "${session_save_path}"
then
	/usr/bin/rm --force --recursive --verbose "${session_save_path}"
fi
/usr/bin/mkdir --mode=0700 --verbose "${session_save_path}"

################################################################################

/usr/bin/php -d "auto_prepend_file=${FILE}" -t "${DOCROOT}" -S "${HOST}:${PORT}"

<?php start:

file_put_contents('php://stderr', "\n");

ini_set('error_reporting', E_ALL);
ini_set('display_errors', '1');
ini_set('html_errors', '1');

set_include_path(
	realpath(
		__DIR__.'/../include'
	)
);
require('block/authorization.php');
require('block/protection.php');
require('block/session.php');
require('block/const.php');

