#!/bin/sh

FILE=`/usr/bin/realpath $0`
DIR=`/usr/bin/dirname ${FILE}`
BASENAME=`basename ${FILE}`

# Help block
#{{{

HELP="
Description: The script drop all tables in MySQL database.
Usage: ${BASENAME} <database>
"

if test "${1}" = "-h" -o "${1}" = "--help"
then
	echo "${HELP}"
	exit 0
fi

#}}}

# Echo functions
#{{{

error ()
{
	/usr/bin/echo "Error: ${BASENAME} - ${1}" >&2
	return 255
}

notice ()
{
	/usr/bin/echo "${BASENAME} - ${1}"
	return 0
}

#}}}

if test -z "${1}"
then
	error "The argument 'database' not passsed in command line"
	exit 255
fi

SQL="SET FOREIGN_KEY_CHECKS = 0; 
SET @database_name = '${1}';
SET @tables = NULL;
SELECT GROUP_CONCAT(table_schema, '.', table_name) INTO @tables
  FROM information_schema.tables 
  WHERE table_schema = @database_name;

SET @tables = CONCAT('DROP TABLE ', @tables);
PREPARE stmt FROM @tables;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
SET FOREIGN_KEY_CHECKS = 1;"

echo "${SQL}" | mysql "${1}"
