#!/bin/sh
unalias -a

HELP="
Description: Download 128kbs mp3 stream of 'silver rain' radio.
Usage: download <path_to_folder_for_save_mp3_file>
"
if test "${1}" = "-h" -o "${1}" = "--help"
then
	echo "${HELP}"
	exit 0
fi

if test -z "${1}"
then
	error "Path to folder for mp3 file is not passed" >&2
	exit 255
fi

export TZ='Europe/Moscow'
export LANG=ru_RU.UTF-8

DATE=`/usr/bin/date "+%a.%H:00"`
/usr/bin/wget -O "${1}/${DATE}.mp3" https://silverrain.hostingradio.ru/silver128.mp3 &
WGET="${!}"
sleep 3600
/usr/bin/kill -SIGTERM "${WGET}"

