<?php

class Main
{

	function __construct()
	{//{{{
	
		if(PHP_SAPI == 'cli') {
			$return = $this->handle_cli();
			if($return !== true) {
				trigger_error("Handle cli failed", E_USER_ERROR);
				exit(255);
			}
			exit(0);
		}
	
		$request_method = @strval($_SERVER["REQUEST_METHOD"]);
		switch($request_method) {
			case('GET'):
				$return = $this->handle_get_request();
				if($return !== true) {
					trigger_error("Handle get request failed", E_USER_ERROR);
					exit(255);
				}
				exit(0);
			case('POST'):
				$return = $this->handle_post_request();
				if($return !== true) {
					trigger_error("Handle post request failed", E_USER_ERROR);
					exit(255);
				}
				exit(0);
			default:
				trigger_error("Unsupported http request method", E_USER_ERROR);
				exit(255);
		}
	}//}}}

	function handle_cli()
	{//{{{//
			
		Args::$description = "Autogenerated site controller";
		Args::add([
			"-T", "--test", NULL, "Tests",
			function ()
			{//{{{//
			
			}//}}}//
			, false]);
		Args::add([
			"-M", "--create-main-tables", NULL, "Create main tables in database",
			function ()
			{//{{{//
				
				$return = Data::create_tables();
				if(!$return) {
					trigger_error("Can't create 'main' tables in database", E_USER_ERROR);
					exit(255);
				}
				user_error("'main' tables in database - created");
				exit(0);
				
			}//}}}//
		, false]);
		Args::add([
			"-J", "--create-job-tables", NULL, "Create tables in database",
			function ()
			{//{{{//
				
				$return = Job::create_tables();
				if(!$return) {
					trigger_error("Can't create 'job' tables", E_USER_ERROR);
				}
				
				exit(0);
				
			},//}}}//
			false
		]);
		Args::add([
			"-U", "--update-events", NULL, "Update events for all tournaments",
			function ()
			{//{{{//
				
				$return = Action::update_events();
				if(!$return) {
					trigger_error("Can't update all 'events'", E_USER_ERROR);
				}
				
				exit(0);
				
			},//}}}//
			false
		]);
		Args::apply();
		
		return(true);
		
	}//}}}//

	function handle_get_request()
	{//{{{
		
		$pattern = '/^.*\/index\.php$/';
		if(preg_match($pattern, URL_PATH) != 1) {
			header('Location: index.php');
			exit(0);
		}
		
		$page = @strval($_GET["page"]);
		
		switch($page) {
		
			case(''):
			$return = Page::index();
			break;
			
// Site ////////////////////////////////////////////////////////////////////////

			case('new_site'):
			$return = Page::new_site();
			break;
			
			case('edit_site'):
			$return = Page::edit_site();
			break;
			
			case('sites_list'):
			$return = Page::sites_list();
			break;
			
// Event ///////////////////////////////////////////////////////////////////////

			case('select_language'):
			$return = Page::select_language();
			break;
			
			case('select_sport'):
			$return = Page::select_sport();
			break;
			
			case('select_tournament'):
			$return = Page::select_tournament();
			break;
			
			case('save_events'):
			$return = Page::save_events();
			break;
			
			case('view_tournament'):
			$return = Page::view_tournament();
			break;
			
			case('tournaments_list'):
			$return = Page::tournaments_list();
			break;
			
			case('view_event'):
			$return = Page::view_event();
			break;
		
// AI //////////////////////////////////////////////////////////////////////////
			
			case('ai_console'):
			$return = Page::ai_console();
			break;
			
			case('get_prediction'):
			$return = Page::get_prediction();
			break;
			
// Job /////////////////////////////////////////////////////////////////////////
			
			case('job_controller'):
			$return = Page::job_controller();
			break;
				
			default:
			if (defined('DEBUG') && DEBUG) var_dump(['$page' => $page]);
			trigger_error("Unsupported page", E_USER_WARNING);
			$return = false;
		}
		
		if($return === false) goto label_error;
		if($return === NULL) goto label_404;
		
		Page::header();
		
		return(true);
		
		label_error:
		if (defined('DEBUG') && DEBUG) var_dump(['page' => $page]);
		trigger_error("Can't create page", E_USER_WARNING);
		return(false);
		
		label_404:
		http_response_code(404);
		die("404 Not found");
	
	}//}}}
	
	function handle_post_request()
	{//{{{
		
		if(!eval(Check::$string.='$_POST["csrf_token"]')) {
			trigger_error("Incorrect post data", E_USER_WARNING);
			return(false);
		}
		
		if(@strval($_POST["csrf_token"]) != CSRF_TOKEN) {
			trigger_error("Incorrect csrf token", E_USER_WARNING);
			return(false);
		}
		
		if(!eval(Check::$string.='$_POST["action"]')) return(false);
		$action = $_POST["action"];
		
		switch($action) {
			case('add_site'):
			$return = Action::add_site();
			break;
		
			case('change_site'):
			$return = Action::change_site();
			break;
		
			case('delete_site'):
			$return = Action::delete_site();
			break;
		
			case('delete_sites'):
			$return = Action::delete_sites();
			break;
			
			// Sport events actions
			
			case('get_languages'):
			$return = Action::get_languages();
			break;
			
			case('get_sports'):
			$return = Action::get_sports();
			break;
			
			case('get_tournaments'):
			$return = Action::get_tournaments();
			break;
			
			case('get_events'):
			$return = Action::get_events();
			break;
			
			case('add_tournament'):
			$return = Action::add_tournament();
			break;
			
			case('change_tournament'):
			$return = Action::change_tournament();
			break;
			
			case('delete_tournament'):
			$return = Action::delete_tournament();
			break;
			
			case('delete_tournaments'):
			$return = Action::delete_tournaments();
			break;
			
			// AI
			
			case('ai_request'):
			$return = Action::ai_request();
			break;
			
			case('get_predictions'):
			$return = Action::get_predictions();
			break;
		
			default:
			if (defined('DEBUG') && DEBUG) var_dump(['$action' => $action]);
			trigger_error("Unsupported action", E_USER_WARNING);
			return(false);
		}
		
		// Error routing
		
		if($return === false) goto label_error;
		if($return === NULL) goto label_404;
		
		return(true);
		
		label_error:
		trigger_error("Action - {$action} failed", E_USER_WARNING);
		return(false);
		
		label_404:
		http_response_code(404);
		die("404 Not found");
		
	}//}}}

}

