#!/bin/sh
#<?php ob_end_clean(); goto start; ?>

VENDOR="ckpunmkug"
PROJECT="console"

FILE=`/usr/bin/realpath $0`
DIR=`/usr/bin/dirname ${FILE}`
BASENAME=`basename ${FILE}`

# Help block
#{{{

HELP="
Description: The script starts the php built-in web server with authorization.
Usage: ${BASENAME} <user_name>
"

if test "${1}" = "-h" -o "${1}" = "--help"
then
	echo "${HELP}"
	exit 0
fi

#}}}

# Echo functions
#{{{

error ()
{
	/usr/bin/echo "Error: ${BASENAME} - ${1}" >&2
	return 255
}

notice ()
{
	/usr/bin/echo "${BASENAME} - ${1}"
	return 0
}

#}}}

# Change user
#{{{

UID=`/usr/bin/id -r -u`
GID=`/usr/bin/id -r -g`

if test $UID -eq 0 -o $GID -eq 0
then
	if test -z "${1}"
	then
		error "User name not set"
		exit 255
	fi
	
	/usr/bin/su -P -s /bin/sh -l "${1}" -c ${FILE}
	exit 0
fi

#}}}

# Load config
#{{{

if test -z "${HOME}"
then
	error "Environment 'HOME' is not set"
	exit 255
fi

export CONFIG_DIR="${HOME}/.config/${VENDOR}/${PROJECT}"
export CACHE_DIR="${HOME}/.cache/${VENDOR}/${PROJECT}"

. "${CONFIG_DIR}/config.sh"

#}}}

# Test variables
#{{{

if test -z "${WEB_SERVER_HOST}"
	then
	error "'WEB_SERVER_HOST' is not set"
	exit 255
fi

if test -z "${WEB_SERVER_PORT}"
	then
	error "'WEB_SERVER_PORT' is not set"
	exit 255
fi

if test -z "${WEB_SERVER_DOCROOT}"
	then
	error "'WEB_SERVER_DOCROOT' is not set"
	exit 255
fi

if test -z "${WEB_SERVER_HASH}"
	then
	error "'WEB_SERVER_HASH' is not set"
	exit 255
fi

#}}}

export WEB_SERVER_HASH="${WEB_SERVER_HASH}"

/usr/bin/php -d auto_prepend_file=${FILE} -t ${WEB_SERVER_DOCROOT} -S ${WEB_SERVER_HOST}:${WEB_SERVER_PORT}
exit $?

<?php start:
require(__DIR__.'/include/block/authorization.php');

