#!/usr/bin/php
<?php

if(true) // Initialization
{//{{{//

	set_include_path(__DIR__.'/../include');
	require_once('class/Data.php');
	require_once('class/Args.php');
	require_once('function/launch.php');
	require_once('component/map.php');
	
}//}}}//

if(true) // Args used chars D, I
{//{{{//
	
	Args::$description = "Scenario";
	Args::add([
		"-D", "--database", "<path_to_file>", "Path to database file",
		function ($string) {
			define("DATABASE_FILE_PATH", $string);
		}, true
	]);
	Args::add([
		"-I", "--input-file", "<path_to_file>", "Path to input file",
		function ($string) {
			define("INPUT_FILE_PATH", $string);
		}, false
	]);
	Args::apply();
	
}//}}}//

function main()
{
	if(true) // open database
	{//{{{//
	
		$return = Data::open(DATABASE_FILE_PATH);
		if(!$return) {
			trigger_error("Can't open database", E_USER_WARNING);
			return(false);
		}
		
	}//}}}//
	if(!true) // rolling
	{//{{{//
		
		$return = map::rolling();
		var_dump($return);
		return(true);
		
	}//}}}//
	if(!true) // 
	{//{{{//
		
		
	}//}}}//
}

$return = main();
if($return !== true) exit(255);
exit(0);

