#!/usr/bin/php
<?php

$home = getenv('HOME');
if(is_string($home)) {
	define('CONFIG_FILE', "{$home}/.config/ckpunmkug/tester.php");
	require_once(CONFIG_FILE);
}
else {
	trigger_error("Can't get `HOME` environment", E_USER_ERROR);
	exit(255);
}

set_include_path(__DIR__.'/../include');
require_once('class/Args.php');

if(true) // Args
{//{{{//

	Args::$description = "PHP Source Tester (gblpokoJL)";
	Args::add([
		"-a", "--action", '<action_name>', "Set script action",
		function ($string) {
			define("TESTER_ACTION", $string);
		}, false
	]);
	Args::add([
		"-c", "--command", '<command_with_line_number>', "Used in less",
		function ($string) {
			define("COMMAND", $string);
		}, false
	]);
	Args::apply();
	
}//}}}//

if(defined('TESTER_ACTION')) 
{//{{{
	switch(TESTER_ACTION) {
		case('search'):
			require_once('component/Search.php');
			$return = Search::main();
			break;
		case('files'):
			require_once('component/Files.php');
			$return = Files::main();
			break;
		case('tracer'):
			require_once('component/Tracer.php');
			$return = Tracer::main();
			break;
		case('debugger'):
			require_once('component/Debugger.php');
			$return = Debugger::main();
			break;
		default:
			trigger_error("Action - '".TESTER_ACTION."' not supported", E_USER_WARNING);
			exit(255);
	}
	if($return !== true) {
		trigger_error("Action - '".TESTER_ACTION."' failed", E_USER_WARNING);
		exit(255);
	}
	exit(0);
}//}}}

if(defined('COMMAND'))
{//{{{//
	require_once('component/Tester.php');
	$return = Tester::main(COMMAND);
	if($return !== true) {
		trigger_error("Tester main call returned an error", E_USER_ERROR);
		exit(255);
	}
	exit(0);
}//}}}//

exit(0);

